apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-resource-constraints
  labels:
    app: deploy-resourcequota-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-resourcequota-test
  template:
    metadata:
      labels:
        app: deploy-resourcequota-test
    spec:
      containers:
      - name: ctr-resource-constrained
        image: nginx
        resources:
          limits:
            cpu: "300m" # 2/3 limit
            #cpu: "1"
            memory: "1Gi"
            # ephemeral-storage: "2Gi"
          requests:
            cpu: "300m" # 2/3 limit
            #cpu: "500m"
            memory: "500m"
            # ephemeral-storage: "1Gi"