kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-ns_alpha-devteam_a-edit
  namespace: ns-alpha
roleRef:
  kind: ClusterRole
  name: edit                             
  apiGroup: rbac.authorization.k8s.io
subjects:
#- kind: Group 
#  name: sso:DevTeamA@lab.local
- kind: User 
  name: sso:Dev01@vsphere.local
  apiGroup: rbac.authorization.k8s.io