apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-1
spec:
  distribution:
    version: v1.18
  topology:
    controlPlane:
      class: guaranteed-small
      count: 1
      storageClass: tanzu
    workers:
      class: guaranteed-small
      count: 1
      storageClass: tanzu
  settings:
    storage:
      classes: ["tanzu"]              #Named PVC storage classes
      defaultClass: tanzu                    #Default PVC storage class
